version: '3.1'

services:
    db:
      image: postgres
      restart: always
      env_file:
        - .env
      environment:
        POSTGRES_USER: kubsu
        POSTGRES_PASSWORD: kubsu
        POSTGRES_DB: kubsu
      ports:
        - "5432:5432"
    app:
      build: .
      ports:
        - "8000:8000"
      depends_on:
        - db
