services:
 db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "5432:5432"
    secrets:
      - db_user
      - db_password
      - db_name
      - db_host
      - db_port
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    secrets:
      - db_user
      - db_password
      - db_name
      - db_host
      - db_port
