name: Docker Image CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build docker images
      uses: docker/build-push-action@v2
      with:
         context: .
         file: ./Dockerfile
         push: false
         tags: myapp:latest
    - name: Test
      run: |
       docker-compose run --rm app pylint main.py test.py
       docker-compose run --rm app python -m unittest test.py
       
