name: Docker Image CI

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: myapp:latest
      - name: Install dependencies
        run: |
          docker-compose run --rm app pip install -r requirements.txt
          docker-compose run --rm app apt-get update && apt-get install -y pylint
      - name: Test
        run: 
          docker-compose run --rm app pylint main.py test.py
